apiVersion: v1
kind: Service
metadata:
  name: kube0
  namespace: prometheus
spec:
  clusterIP: None
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: kube1
  namespace: prometheus
spec:
  clusterIP: None
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: kube2
  namespace: prometheus
spec:
  clusterIP: None
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: kube3
  namespace: prometheus
spec:
  clusterIP: None
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: jetson
  namespace: prometheus
spec:
  clusterIP: None
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: kube0
  namespace: prometheus
subsets:
- addresses:
  - ip: 10.10.0.1
  ports:
  - port: 1
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: kube1
  namespace: prometheus
subsets:
- addresses:
  - ip: 10.10.0.101
  ports:
  - port: 1
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: kube2
  namespace: prometheus
subsets:
- addresses:
  - ip: 10.10.0.102
  ports:
  - port: 1
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: kube3
  namespace: prometheus
subsets:
- addresses:
  - ip: 10.10.0.103
  ports:
  - port: 1
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: kube3
  namespace: prometheus
subsets:
- addresses:
  - ip: 10.10.0.104
  ports:
  - port: 1
    protocol: TCP
