apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: prom-kasa
  name: prom-kasa
  namespace: prometheus
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: prom-kasa
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/port: "8000"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: prom-kasa
    spec:
      containers:
      - command:
        - python3
        - /prom_kasa.py
        image: burns.azurecr.io/prom-kasa:v5
        imagePullPolicy: IfNotPresent
        name: prom-kasa
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: tz-seattle
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: pull-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/US/Pacific
          type: ""
        name: tz-seattle
