apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
    chart: prometheus-9.3.1
    component: server
    heritage: Helm
    release: prometheus
  name: prometheus-server
  namespace: prometheus
spec:
  clusterIP: 10.96.174.174
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
    component: server
    release: prometheus
  sessionAffinity: None
  type: ClusterIP
